pipeline {
    agent any
    stages {
        stage('Clone repo from main') {
            steps {
                git branch: 'main',
                    credentialsId: 'GitHub_SSH_Key_jenkins',
                    url: 'git@github.com:YuriyPelykh/spring-petclinic.git'
                sh "ls -lat"
            }
        }
        stage('Static code analysis') {
            steps {
                echo "Stage in development..."
            }
        }

        stage('Pre-build Testing-DB creation') {
            steps {
                sh "docker-copmpose up -d mysql"
                echo "Stage in development..."
            }
        }

        stage('Build Docker-image') {
            steps {
                echo "Stage in development..."
            }
        }

        stage('Post-build config') {
            steps {
                echo "Stage in development..."
            }
        }

        stage('Push image into repository') {
            steps {
                echo "Stage in development..."
            }
        }
    }
}

